<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mohammads-MacBook-Air.local" failures="3" tests="6" name="Test" time="59.778" errors="0" timestamp="2025-03-16T12:37:18 GMT">
  <testcase classname="tests.LogoutUser" name="logout" time="5.434"/>
  <testcase classname="tests.RegisterUserExistingEmail" name="existingEmailRegister" time="3.578"/>
  <testcase classname="tests.LoginUser" name="Login" time="14.107">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Success&amp;gt; but was:&amp;lt;Failure&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Success> but was:<Failure>
at tests.LoginUser.Login(LoginUser.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="tests.LoginUser" name="Login" time="14.179"/>
  <testcase classname="tests.Failintentional" name="failedTest" time="2.981">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at tests.Failintentional.failedTest(Failintentional.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- failedTest -->
  <testcase classname="tests.RegisterUserFresh" name="userRegister" time="1.324">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.sendKeys(Unknown Source)
at tests.RegisterUserFresh.userRegister(RegisterUserFresh.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- userRegister -->
</testsuite> <!-- Test -->
