<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mohammads-MacBook-Air.local" failures="1" tests="1" name="Test1" time="3.621" errors="0" timestamp="2025-03-12T12:49:30 GMT">
  <testcase classname="tests.Failintentional" name="failedTest" time="3.204">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at tests.Failintentional.failedTest(Failintentional.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- failedTest -->
</testsuite> <!-- Test1 -->
